<a href="https://colab.research.google.com/github/LiyaAg/Python-Basics-/blob/main/Pandas_and_numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
#for uploading a file in google collab 
from google.colab import files
supermarket=files.upload()

Saving Supermarket_sales.csv to Supermarket_sales.csv


In [9]:
#Reading and Displaying CSV files as DataFrames
import pandas
dataframe=pandas.read_csv("Supermarket_sales.csv")
print(dataframe)

       No    InvoiceID Branch       City Customertype  Gender  \
0       1  750-67-8428      A     Yangon       Member  Female   
1       2  226-31-3081      C  Naypyitaw       Normal  Female   
2       3  631-41-3108      A     Yangon       Normal    Male   
3       4  123-19-1176      A     Yangon       Member    Male   
4       5  373-73-7910      A     Yangon       Normal    Male   
..    ...          ...    ...        ...          ...     ...   
995   996  233-67-5758      C  Naypyitaw       Normal    Male   
996   997  303-96-2227      B   Mandalay       Normal  Female   
997   998  727-02-1313      A     Yangon       Member    Male   
998   999  347-56-2442      A     Yangon       Normal    Male   
999  1000  849-09-3807      A     Yangon       Member  Female   

                Productline  Unitprice  Quantity      Tax      Total  \
0         Health and beauty      74.69         7  26.1415   548.9715   
1    Electronic accessories      15.28         5   3.8200    80.2200   
2  

In [11]:
#printing first 10 rows of DataFrame
dataframe=pandas.read_csv("Supermarket_sales.csv")
print(dataframe.head(10))

   No    InvoiceID Branch       City Customertype  Gender  \
0   1  750-67-8428      A     Yangon       Member  Female   
1   2  226-31-3081      C  Naypyitaw       Normal  Female   
2   3  631-41-3108      A     Yangon       Normal    Male   
3   4  123-19-1176      A     Yangon       Member    Male   
4   5  373-73-7910      A     Yangon       Normal    Male   
5   6  699-14-3026      C  Naypyitaw       Normal    Male   
6   7  355-53-5943      A     Yangon       Member  Female   
7   8  315-22-5665      C  Naypyitaw       Normal  Female   
8   9  665-32-9167      A     Yangon       Member  Female   
9  10  692-92-5582      B   Mandalay       Member  Female   

              Productline  Unitprice  Quantity      Tax     Total       Date  \
0       Health and beauty      74.69         7  26.1415  548.9715   1/5/2019   
1  Electronic accessories      15.28         5   3.8200   80.2200   3/8/2019   
2      Home and lifestyle      46.33         7  16.2155  340.5255   3/3/2019   
3       

In [12]:
#printing last 8 rows of DataFrame
dataframe=pandas.read_csv("Supermarket_sales.csv")
print(dataframe.tail(8))

       No    InvoiceID Branch       City Customertype  Gender  \
992   993  745-74-0715      A     Yangon       Normal    Male   
993   994  690-01-6631      B   Mandalay       Normal    Male   
994   995  652-49-6720      C  Naypyitaw       Member  Female   
995   996  233-67-5758      C  Naypyitaw       Normal    Male   
996   997  303-96-2227      B   Mandalay       Normal  Female   
997   998  727-02-1313      A     Yangon       Member    Male   
998   999  347-56-2442      A     Yangon       Normal    Male   
999  1000  849-09-3807      A     Yangon       Member  Female   

                Productline  Unitprice  Quantity      Tax      Total  \
992  Electronic accessories      58.03         2   5.8030   121.8630   
993     Fashion accessories      17.49        10   8.7450   183.6450   
994  Electronic accessories      60.95         1   3.0475    63.9975   
995       Health and beauty      40.35         1   2.0175    42.3675   
996      Home and lifestyle      97.38        10  48.6

In [13]:
#printing a specific row
#printing the second row 
dataframe.loc[1]

No                                              2
InvoiceID                             226-31-3081
Branch                                          C
City                                    Naypyitaw
Customertype                               Normal
Gender                                     Female
Productline                Electronic accessories
Unitprice                                   15.28
Quantity                                        5
Tax                                          3.82
Total                                       80.22
Date                                     3/8/2019
Time                                        10:29
Payment                                      Cash
cogs                                         76.4
gross_margin_percentage                  4.761905
gross_iincome                                3.82
Rating                                        9.6
Name: 1, dtype: object

In [14]:
#printing the fourth row 
dataframe.loc[3]


No                                         4
InvoiceID                        123-19-1176
Branch                                     A
City                                  Yangon
Customertype                          Member
Gender                                  Male
Productline                Health and beauty
Unitprice                              58.22
Quantity                                   8
Tax                                   23.288
Total                                489.048
Date                               1/27/2019
Time                                   20:33
Payment                              Ewallet
cogs                                  465.76
gross_margin_percentage             4.761905
gross_iincome                         23.288
Rating                                   8.4
Name: 3, dtype: object

In [15]:
#printing city 
dataframe['City']

0         Yangon
1      Naypyitaw
2         Yangon
3         Yangon
4         Yangon
         ...    
995    Naypyitaw
996     Mandalay
997       Yangon
998       Yangon
999       Yangon
Name: City, Length: 1000, dtype: object

In [16]:
#printing two columns
dataframe[['City','Branch']]

City Branch
0       Yangon      A
1    Naypyitaw      C
2       Yangon      A
3       Yangon      A
4       Yangon      A
..         ...    ...
995  Naypyitaw      C
996   Mandalay      B
997     Yangon      A
998     Yangon      A
999     Yangon      A

[1000 rows x 2 columns]

In [17]:
#dropping specific column drop([column name],axis=1)  #0 is for rows and 1 is for columns
dataframe=dataframe.drop(['Tax'],axis=1)
dataframe.head(4)

No    InvoiceID Branch       City Customertype  Gender  \
0   1  750-67-8428      A     Yangon       Member  Female   
1   2  226-31-3081      C  Naypyitaw       Normal  Female   
2   3  631-41-3108      A     Yangon       Normal    Male   
3   4  123-19-1176      A     Yangon       Member    Male   

              Productline  Unitprice  Quantity     Total       Date   Time  \
0       Health and beauty      74.69         7  548.9715   1/5/2019  13:08   
1  Electronic accessories      15.28         5   80.2200   3/8/2019  10:29   
2      Home and lifestyle      46.33         7  340.5255   3/3/2019  13:23   
3       Health and beauty      58.22         8  489.0480  1/27/2019  20:33   

       Payment    cogs  gross_margin_percentage  gross_iincome  Rating  
0      Ewallet  522.83                 4.761905        26.1415     9.1  
1         Cash   76.40                 4.761905         3.8200     9.6  
2  Credit card  324.31                 4.761905        16.2155     7.4  
3      Ewallet  465.76                 4.761905        23.2880     8.4

In [22]:
dataframe=dataframe.drop(['gross_margin_percentage'],axis=1)
dataframe.head(4)

No    InvoiceID Branch       City Customertype  Gender  \
0   1  750-67-8428      A     Yangon       Member  Female   
1   2  226-31-3081      C  Naypyitaw       Normal  Female   
2   3  631-41-3108      A     Yangon       Normal    Male   
3   4  123-19-1176      A     Yangon       Member    Male   

              Productline  Unitprice  Quantity     Total       Date   Time  \
0       Health and beauty      74.69         7  548.9715   1/5/2019  13:08   
1  Electronic accessories      15.28         5   80.2200   3/8/2019  10:29   
2      Home and lifestyle      46.33         7  340.5255   3/3/2019  13:23   
3       Health and beauty      58.22         8  489.0480  1/27/2019  20:33   

       Payment  gross_iincome  Rating  
0      Ewallet        26.1415     9.1  
1         Cash         3.8200     9.6  
2  Credit card        16.2155     7.4  
3      Ewallet        23.2880     8.4

In [ ]:
#dropping specific row drop([index],axis=0)

In [33]:
dataframe=pandas.read_csv("Supermarket_sales.csv")
max_Unitprice=dataframe.Unitprice.idxmax()
print(max_Unitprice)

122


In [34]:
dataframe.Unitprice.max()
#most expensive

99.96

In [35]:
dataframe.Unitprice.idxmax()
# the index number of the row

122

In [36]:
dataframe.Unitprice.idxmin()
# the index number of the row

944

In [37]:
dataframe.Unitprice.min()
#cheapest 


10.08

In [38]:
# printing the average of a specific column 
dataframe.Unitprice.mean()

55.67213

In [39]:
#printing the details of all the normal customers
dataframe.loc[dataframe['Customertype'] == "Normal"]

No    InvoiceID Branch       City Customertype  Gender  \
1      2  226-31-3081      C  Naypyitaw       Normal  Female   
2      3  631-41-3108      A     Yangon       Normal    Male   
4      5  373-73-7910      A     Yangon       Normal    Male   
5      6  699-14-3026      C  Naypyitaw       Normal    Male   
7      8  315-22-5665      C  Naypyitaw       Normal  Female   
..   ...          ...    ...        ...          ...     ...   
992  993  745-74-0715      A     Yangon       Normal    Male   
993  994  690-01-6631      B   Mandalay       Normal    Male   
995  996  233-67-5758      C  Naypyitaw       Normal    Male   
996  997  303-96-2227      B   Mandalay       Normal  Female   
998  999  347-56-2442      A     Yangon       Normal    Male   

                Productline  Unitprice  Quantity      Tax      Total  \
1    Electronic accessories      15.28         5   3.8200    80.2200   
2        Home and lifestyle      46.33         7  16.2155   340.5255   
4         Sports and travel      86.31         7  30.2085   634.3785   
5    Electronic accessories      85.39         7  29.8865   627.6165   
7        Home and lifestyle      73.56        10  36.7800   772.3800   
..                      ...        ...       ...      ...        ...   
992  Electronic accessories      58.03         2   5.8030   121.8630   
993     Fashion accessories      17.49        10   8.7450   183.6450   
995       Health and beauty      40.35         1   2.0175    42.3675   
996      Home and lifestyle      97.38        10  48.6900  1022.4900   
998      Home and lifestyle      65.82         1   3.2910    69.1110   

          Date   Time      Payment    cogs  gross_margin_percentage  \
1     3/8/2019  10:29         Cash   76.40                 4.761905   
2     3/3/2019  13:23  Credit card  324.31                 4.761905   
4     2/8/2019  10:37      Ewallet  604.17                 4.761905   
5    3/25/2019  18:30      Ewallet  597.73                 4.761905   
7    2/24/2019  11:38      Ewallet  735.60                 4.761905   
..         ...    ...          ...     ...                      ...   
992  3/10/2019  20:46      Ewallet  116.06                 4.761905   
993  2/22/2019  18:35      Ewallet  174.90                 4.761905   
995  1/29/2019  13:46      Ewallet   40.35                 4.761905   
996   3/2/2019  17:16      Ewallet  973.80                 4.761905   
998  2/22/2019  15:33         Cash   65.82                 4.761905   

     gross_iincome  Rating  
1           3.8200     9.6  
2          16.2155     7.4  
4          30.2085     5.3  
5          29.8865     4.1  
7          36.7800     8.0  
..             ...     ...  
992         5.8030     8.8  
993         8.7450     6.6  
995         2.0175     6.2  
996        48.6900     4.4  
998         3.2910     4.1  

[499 rows x 18 columns]

In [40]:
# printing the details of males 
dataframe.loc[dataframe['Gender'] == "Male"]

No    InvoiceID Branch       City Customertype Gender  \
2      3  631-41-3108      A     Yangon       Normal   Male   
3      4  123-19-1176      A     Yangon       Member   Male   
4      5  373-73-7910      A     Yangon       Normal   Male   
5      6  699-14-3026      C  Naypyitaw       Normal   Male   
11    12  529-56-3974      B   Mandalay       Member   Male   
..   ...          ...    ...        ...          ...    ...   
992  993  745-74-0715      A     Yangon       Normal   Male   
993  994  690-01-6631      B   Mandalay       Normal   Male   
995  996  233-67-5758      C  Naypyitaw       Normal   Male   
997  998  727-02-1313      A     Yangon       Member   Male   
998  999  347-56-2442      A     Yangon       Normal   Male   

                Productline  Unitprice  Quantity      Tax     Total  \
2        Home and lifestyle      46.33         7  16.2155  340.5255   
3         Health and beauty      58.22         8  23.2880  489.0480   
4         Sports and travel      86.31         7  30.2085  634.3785   
5    Electronic accessories      85.39         7  29.8865  627.6165   
11   Electronic accessories      25.51         4   5.1020  107.1420   
..                      ...        ...       ...      ...       ...   
992  Electronic accessories      58.03         2   5.8030  121.8630   
993     Fashion accessories      17.49        10   8.7450  183.6450   
995       Health and beauty      40.35         1   2.0175   42.3675   
997      Food and beverages      31.84         1   1.5920   33.4320   
998      Home and lifestyle      65.82         1   3.2910   69.1110   

          Date   Time      Payment    cogs  gross_margin_percentage  \
2     3/3/2019  13:23  Credit card  324.31                 4.761905   
3    1/27/2019  20:33      Ewallet  465.76                 4.761905   
4     2/8/2019  10:37      Ewallet  604.17                 4.761905   
5    3/25/2019  18:30      Ewallet  597.73                 4.761905   
11    3/9/2019  17:03         Cash  102.04                 4.761905   
..         ...    ...          ...     ...                      ...   
992  3/10/2019  20:46      Ewallet  116.06                 4.761905   
993  2/22/2019  18:35      Ewallet  174.90                 4.761905   
995  1/29/2019  13:46      Ewallet   40.35                 4.761905   
997   2/9/2019  13:22         Cash   31.84                 4.761905   
998  2/22/2019  15:33         Cash   65.82                 4.761905   

     gross_iincome  Rating  
2          16.2155     7.4  
3          23.2880     8.4  
4          30.2085     5.3  
5          29.8865     4.1  
11          5.1020     6.8  
..             ...     ...  
992         5.8030     8.8  
993         8.7450     6.6  
995         2.0175     6.2  
997         1.5920     7.7  
998         3.2910     4.1  

[499 rows x 18 columns]

In [41]:
#creating 1 dimensional array from list 
import numpy as np
student_marks_BA=[12,14,20]
marksarray=np.array(student_marks_BA)
print(marksarray)


[12 14 20]


In [42]:
#Creating nd array from list to list 
import numpy as np
student_marks=[[12,14,20],[16,12,13],[10,9,19]]
marksarray=np.array(student_marks)
print(marksarray)

[[12 14 20]
 [16 12 13]
 [10  9 19]]


In [44]:
# 4 rows and 2 columns 
import numpy as np
student_marks=[[12,14],[16,12],[10,9],[10,12]]
marksarray=np.array(student_marks)
print(marksarray)

[[12 14]
 [16 12]
 [10  9]
 [10 12]]


In [45]:
#shape of an existing array
marksarray.shape

(4, 2)

In [49]:
#creating evenly spaced array using ARANGE
values1=np.arange(20)
print(values1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [50]:
#between a given range
values1=np.arange(1,11)
print(values1)

[ 1  2  3  4  5  6  7  8  9 10]


In [51]:
#skipping the step count
values1=np.arange(1,11,2)
print(values1)

[1 3 5 7 9]


In [53]:
values1=np.arange(50,61)
print(values1)

[50 51 52 53 54 55 56 57 58 59 60]


In [54]:
values1=np.arange(70,101,3)
print(values1)

[ 70  73  76  79  82  85  88  91  94  97 100]


In [55]:
#creating zero array
zeroarray=np.zeros(8)
print(zeroarray)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [57]:
zeroarray=np.zeros((4,2))
print(zeroarray)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [59]:
#creating ones array
onesarray=np.ones(6)
print(onesarray)

[1. 1. 1. 1. 1. 1.]


In [61]:
onesarray=np.ones((8,2))
print(onesarray)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [62]:
#creating 2D identity matrix using eye()
identityarray=np.eye(5)
print(identityarray)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [63]:
identityarray=np.eye(10)
print(identityarray)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [65]:
#finding the length of array
len(zeroarray)

4

In [69]:
#reshaping an array
firstarray=np.array([[10,20,30],[2,4,6],[5,10,15],[15,16,17]])
print(firstarray)

[[10 20 30]
 [ 2  4  6]
 [ 5 10 15]
 [15 16 17]]


In [73]:
secondary=firstarray.reshape(3,4)
print(secondary)

[[10 20 30  2]
 [ 4  6  5 10]
 [15 15 16 17]]


In [74]:
#creating an array with random functions 
values=np.random.randint(1,3,5)
print(values )

[1 2 1 1 2]


In [75]:
values=np.random.randint(1,20,8)
print(values)

[16  3  6 18 10  4  6 16]


In [76]:
values=np.random.randint(44,88,6)
print(values)

[49 73 76 64 55 84]


In [78]:
values=np.random.randint(25,50,(4,3))
print(values)

[[41 46 46]
 [36 46 35]
 [38 41 28]
 [40 26 37]]
